{% set name = "pygments-cache" %}
{% set version = "0.1.2" %}
{% set sha256 = "6a0db9dcc430d321a6491536e9b8ac28d74396f1c87807d8fdc77b185319ec32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xonsh/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pygments

test:
  imports:
    - pygments_cache

about:
  home: https://github.com/xonsh/pygments-cache
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A fast, drop-in replacement for pygments get_*() and guess_*() funtions.'

extra:
  recipe-maintainers:
    - scopatz
