{% set name = "pygments-cache" %}
{% set version = "0.1.3" %}
{% set sha256 = "01568c8dbd4c8853c82de644b2843af28631c8d745f8e57c31fe2ab7bbf9c9e8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xonsh/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pygments

test:
  imports:
    - pygments_cache

about:
  home: https://github.com/xonsh/pygments-cache
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A fast, drop-in replacement for pygments get_*() and guess_*() funtions.'

extra:
  recipe-maintainers:
    - scopatz
