travis:
  secure:
    BINSTAR_TOKEN: KvZwZ01A96W0A6MEqHLmxyLCkffK6ElV6UVN6Q9SeIGze72IDmws9T+S6x/VV4b2SLOhZN0KyuQ83JKzANFysMp2E0NBNIubC6m8Iq1MOH2j8lMvu4ezPqACbqZK244GCLs52EJHFI0/neC914Gj6+Mm6AEuF35bizA5AEjCsY6QsKlCYg1Hsviv293mEr9LjvBcqsYk2I4rYVSHEBauSOm0EPz/An/i+TmxefU7A9tvLSpFxzDKQayBLJ795XurraO2EzJCF0Je52HEeoplfqEZ9saJWHTJTBT3BIf8G8rBVe/H/3yoMXHKPKyxSVJfqVYKKFz1r7nKqfSXJl9CxWHR7rTPS8mu5Elni5+gplDLEt4dmxu2j3tvbofYS4P5prBO+zxHUFbsW7Wupi6ml2BMRuBTpNUgLF7qNqiUuMQPZ0R2Zg25iK3NdcfbyAG9OLuYPF8rw1nRUGRDDPhYp7Tn9JvfhC++7M9ldWL8fNFL4Mu5smgskEoYHJRfTwxZlHW2YMbRDM0Losan+d2E1OubmB5LoDloXhNqkmD5D8VcU+P/xNv3d4EjzhctA4SlVHgpvTbwtJaeW0q7fDoWMw79ae5dB27p2tAzKXHu5h2KzhNPUR4MeStSHzNVV6V5g2lQyLPidaFkGQnqZ2gSGl+6ZifwjteKVhdsS4uBkiw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
