travis:
  secure:
    BINSTAR_TOKEN: R3N++j9q7EtXPitYo7z26jpjOw04ot6Z67jOVDXMOwRm1SjmcFuW7r3JTGfpkaUT2+fuLv3pI/JVq02nWYlOHNwlFDLy1ZoTcWx4skWA9IB0bjQEXK4qh1F5EIgkGtqm8VU81U3vnOkTqChGqkxNSEOfE8Zr/VWE0ooc2LXiAiDkDgrsDFM3rZn9zNaKxaYwnvmbKaaBO/3qjWJdUK6gktfFae7OIQcv+/a5kCbBFrLDD3rUabn1vRHzygTasRJZBMTWLlh5V0VwpLZdzpz2KhS7L+4+hjsbiJHgVyggFD0AFM1yNQa2MBWRGkLhSFhTFyjrlYcOJdXgBkjdjPWgDFi3vB7oFibp9DYmU6CytZtgthpS7XEgGVAixA3CbUPjd4hI9zRuypyGh7EFL5T3TwC2KVXkiMrvHvqn/389TdRQTFltJe2FRSjxLZ6fWKEjinOCWAx5v/FPd/CfQmdyha/rgYERnqGDtO3KJ10rZpeJXRLl4OYPs/NjzV/W2woL/Bw9yJDAshqs9YclmMUiKHatd95Plnyo/WGwIVWlZ7MMf4WJVrzRvY4hjVrUrESw1v7+uo2ZCVXV6aqBYkJVvU5OuSrmmPrx9wNDY+Jcfye+8yhFxtF/jDnR3VFOoOJ9BLA/bmwyKNc/9Rl1GgM8ztC89w5pUuDaEsVvd68Ld9c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
